<?php

namespace CasinoGoldBundle\Repository;

/**
 * CardColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardColorRepository extends \Doctrine\ORM\EntityRepository
{
}
